version: '3'
services:
  plugin_browser:
    build: .
    container_name: plugin_browser
    environment:
        - ANNOUNCEMENT_CHANNEL=CHANNEL_ID_FOR_PLUGIN_SHARE
        - APPROVAL_CHANNEL=CHANNEL_ID_FOR_ADMIN_APPROVAL
        - DISCORD_TOKEN=DISCORD_BOT_TOKEN
        - DB_PATH=/db/plugin_store.db
        - B2_APP_KEY_ID=FOR_IMAGE_UPLOAD
        - B2_APP_KEY=FOR_IMAGE_UPLOAD
        - B2_BUCKET_ID=FOR_IMAGE_UPLOAD
    volumes:
        - ~/database:/db
    networks:
        - plugins-network
    restart: unless-stopped

networks:
  plugins-network:
    driver: bridge
