version: '3'
services:
  plugin_store:
    build: .
    container_name: plugin_store
    environment:
        - DB_PATH=/db/plugin_store.db
        - ANNOUNCEMENT_WEBHOOK=A_DISCORD_WEBHOOK_URL_FOR_PLUGIN_SHARE
        - SUBMIT_AUTH_KEY=A_SHARED_KEY_BETWEEN_THE_BUILD_SERVICE_AND_STORE
        - B2_APP_KEY_ID=FOR_IMAGE_UPLOAD
        - B2_APP_KEY=FOR_IMAGE_UPLOAD
        - B2_BUCKET_ID=FOR_IMAGE_UPLOAD
    volumes:
        - ~/database:/db
    networks:
        - plugins-network
    restart: unless-stopped

networks:
  plugins-network:
    driver: bridge